/* exported JCProfiles */

/**
 * Settings of the sites the plugin knows: adapter, params and notes, found by the address of
 * the journal. They are used when a journal is added ("Aggiungi rivista…", "Rileva
 * automaticamente") or imported with only title and url — never to add journals by themselves.
 *
 * match: address prefixes (host without www, path, lower case) — the longest match wins.
 */
var JCProfiles = {
	SITES: [
		{"match": ["aedon.mulino.it"], "adapter": "aedon", "params": {"htmlToPdf": true}, "notes": "Rivista di arti e diritto on line (il Mulino). Legge l'indice di ogni fascicolo (1998-oggi, 3 numeri l'anno). Dal 2019 (n. 2) ogni articolo ha DOI e il PDF, ad accesso aperto, viene scaricato da Rivisteweb; gli articoli precedenti esistono solo come pagine HTML e vengono salvati come pagina web (snapshot). Esclusa la sezione 'Documenti' (testi di leggi e sentenze) e la pagina 'Gli autori'. La sezione 'Atti' della home (convegni) non è inclusa. Il titolo inglese è riportato nel campo Extra."},
		{"match": ["oaj.fupress.net/index.php/ceset"], "adapter": "aestimum", "params": {"base": "https://oaj.fupress.net/index.php/ceset", "skipPattern": "^(copertina|indice$|frontespizio - indice$|elenco (delle )?pubblicazioni|norme (editoriali|per la pubblicazione)|sommario - résumé)|: indice$"}, "notes": "Rivista di estimo ed economia agraria (Firenze University Press, OJS). Scarica tutti gli articoli via OAI-PMH, compreso l'archivio digitalizzato dal 1977 (volumi, Seminari, Quaderni, Atti degli Incontri di Studio CeSET), con PDF. Esclusi copertine, frontespizi, indici, norme editoriali ed elenchi delle pubblicazioni. Per l'archivio storico l'anno è ricavato dal fascicolo (il sito indica come data quella della digitalizzazione, 2009) e il fascicolo è indicato come 'Seminari 13', 'Atti del XX Incontro di Studio' ecc. Gli articoli pubblicati come 'Just Accepted' vengono importati subito, senza volume. Molti contributi storici hanno titoli generici ('Intervento', 'Rubriche')."},
		{"match": ["affarinternazionali.it"], "adapter": "wordpress", "params": {"base": "https://www.affarinternazionali.it", "query": {"categories_exclude": "188,192,202,203,833"}, "requirePdf": false, "pdfSelector": "a.jc-no-article-pdf", "htmlToPdf": true}, "notes": "Magazine on-line dell'IAI: gli articoli sono solo pagine HTML (nessun PDF per articolo), quindi viene salvata un'istantanea della pagina web. Esclusi podcast, video, vignette, agenda internazionale e annunci. La pubblicazione risulta ferma dal maggio 2026 (numero speciale '20 anni di AffarInternazionali'); l'archivio su questo sito parte dal settembre 2021 (gli anni precedenti sono nell''Archivio storico' del vecchio sito, non coperto). Autori non disponibili."},
		{"match": ["ambientediritto.it"], "adapter": "crawl", "params": {"start": "https://www.ambientediritto.it/?post_type=dottrina", "articleSelector": "div.blocco-archivio", "linkSelector": "h4 a", "titleSelector": "h4 a", "titlePattern": "Anno:\\s*(?<date>\\d{4})\\s*Autore:\\s*(?<authors>.*)$", "nextSelector": "a.wpv-archive-pagination-links-next-link", "skipPattern": "Rivista Scientifica di Fascia|Fascicolo n\\.|anni precedenti", "landing": true}, "notes": "Viene scaricata la sezione Dottrina (tipo di contenuto 'dottrina', non esposto nella REST API) dall'archivio https://www.ambientediritto.it/?post_type=dottrina (25 per pagina, più recenti prima); il PDF ('Scarica allegato') è nella pagina dell'articolo. Della data è disponibile solo l'anno. Esclusi i fascicoli interi e la giurisprudenza. Gli autori vengono dal campo 'Autore' dell'elenco (con più autori separati da trattino possono risultare imprecisi)."},
		{"match": ["amministrativamente.com/index.php/formez", "amministrativamente.com"], "adapter": "crawl", "params": {"start": "https://www.amministrativamente.com/index.php/formez/issue/archive", "issueSelector": "h4 a[href*=\"/issue/view/\"]", "articleSelector": "table.tocArticle", "titleSelector": ".tocTitle", "linkSelector": ".tocTitle a", "pdfSelector": "a.file", "authorsSelector": ".tocAuthors", "skipPattern": "^Fascicolo\\b"}, "notes": "Rivista di ateneo dell'Università di Roma 'Foro Italico' (OJS 2). Scarica tutti i fascicoli dall'archivio (dal 2009): saggi, segnalazioni di giurisprudenza, anticipazioni, con PDF. Esclusi i PDF del 'Fascicolo integrale' e la raccolta 'Focus tematico' (ripubblica articoli già usciti). Metadati dal sommario del fascicolo: titolo, autori, anno e numero del fascicolo ('N. 2 (2026)'). Gli articoli 'Anticipazioni del prossimo numero' a volte vengono ripubblicati nel fascicolo successivo come nuovo articolo: il controllo duplicati di Zotero (titolo+anno) ne intercetta la maggior parte."},
		{"match": ["amministrazioneincammino.luiss.it"], "adapter": "wordpress", "params": {"base": "https://www.amministrazioneincammino.luiss.it", "query": {"categories_exclude": "4,5,6,7,9,11,12,13,17,18,19,20,22,23,26,27,30,34,35,36,37,38,39,40,41,42,43,44,45,48,49,54,59,64,87,88,100,107,123,131,143,156,216,217"}}, "notes": "Post WordPress con PDF allegato. Sono escluse le categorie non scientifiche (segnalazioni, giurisprudenza/sentenze, convegni e resoconti, novità editoriali, Quaderni della rivista); i post senza PDF (vecchie schede, recensioni solo HTML) sono saltati. Comprende i fascicoli dal 2018, la sezione 'Forum' e le note e commenti dal 2001. Autori non disponibili nei dati del sito."},
		{"match": ["brill.com/view/journals/arlp/arlp-overview.xml", "arcticreview.no/index.php/arctic"], "adapter": "arctic-review-law-politics", "params": {}, "notes": "Dal 2025 la rivista è pubblicata da Brill (ad accesso aperto); il vecchio sito arcticreview.no rimanda a Brill, dove è stato trasferito anche l'archivio dal 2010 (vol. 1). Un volume l'anno (vol. N = anno 2009+N): legge l'indice di ogni volume e la lista 'Early view' (articoli dell'anno in corso non ancora assegnati al volume); metadati completi (autori, data, DOI, pagine, abstract) dalle pagine degli articoli. Quando un articolo passa da Early view al volume cambia indirizzo ma non DOI: il controllo dei duplicati per DOI evita doppioni. Esclusi front/back matter."},
		{"match": ["journals.uniurb.it/index.php/argomenti"], "adapter": "ojs", "params": {"base": "https://journals.uniurb.it/index.php/argomenti", "excludeSets": ["COP"], "skipPattern": "^copertina"}, "notes": "Rivista di economia, cultura e ricerca sociale (Università di Urbino, OJS). Scarica tutti gli articoli dal 2015 via OAI-PMH con PDF; esclusi copertine e sommari. Metadati completi: titolo, autori, data, numero, pagine, DOI."},
		{"match": ["astrid-online.it/rassegna"], "adapter": "crawl", "params": {"start": "https://www.astrid-online.it/rassegna/index.html"}, "enabled": false, "notes": "Rivista quindicinale della Fondazione Astrid. Gli articoli ('Studi, ricerche, articoli e relazioni') sono PDF nell'area riservata (/static/upload/protected/…): senza login il sito rimanda alla pagina di accesso. Liberi sono solo i documenti istituzionali segnalati nella rassegna (rapporti, sentenze, atti di organismi terzi), che non sono articoli della rivista. Disattivata perché richiede abbonamento."},
		{"match": ["athena.unibo.it"], "adapter": "ojs", "params": {"base": "https://athena.unibo.it"}, "notes": "Athena – Critical Inquiries in Law, Philosophy and Globalization (Università di Bologna, OJS). Scarica tutti i contributi dal 2021 via OAI-PMH con PDF: saggi, editoriali/foreword, miscellanea, atti di convegno e recensioni. Metadati completi (volume, numero, pagine, DOI)."},
		{"match": ["athensjournals.gr/ajl", "atiner.gr/journals/law.htm"], "adapter": "crawl", "params": {"start": "https://www.athensjournals.gr/ajl/past", "issueSelector": ".entry-content a[href*=\"/ajl/\"]", "issuePattern": "/ajl/(past/)?v\\d+i\\d+/?$", "articleSelector": ".entry-content tr", "titleSelector": "td.column-1 strong a", "pdfSelector": "td.column-1 a[href$=\".pdf\"]", "skipPattern": "^(front pages|cover|back pages|download the entire)", "issueFromLabel": false}, "notes": "Rivista trimestrale dell'ATINER (Atene), ad accesso aperto; il vecchio indirizzo atiner.gr rimanda a athensjournals.gr (WordPress). Legge l'elenco dei fascicoli (dal 2015) e l'indice di ciascuno; PDF di ogni articolo. Esclusi frontespizi e PDF dell'intero fascicolo. Metadati: titolo e data (mese/anno del fascicolo); gli autori non vengono letti (sono nel PDF)."},
		{"match": ["berkeleyjournalofinternationallaw.com", "scholarship.law.berkeley.edu/bjil"], "adapter": "berkeley-international-law", "params": {}, "notes": "La rivista ha lasciato Digital Commons (scholarship.law.berkeley.edu/bjil ora dà 404): il sito ufficiale (Wix) rimanda per ogni articolo a LawCat, il repository di Berkeley Law. Si raccolgono via OAI-PMH (MARCXML) tutti i record delle riviste di Berkeley Law e si tengono solo quelli di questa rivista: titolo, autori, data, volume, fascicolo, prima pagina, DOI. Esclusi full issue, front matter, masthead, indici. La prima esecuzione legge l'intero set (~10.000 record, circa 4-7 minuti); le successive solo i record modificati. I PDF su LawCat sono protetti da AWS WAF: in Zotero vengono scaricati tramite il browser nascosto; se non riesce l'elemento resta senza allegato."},
		{"match": ["centroeinaudi.it/biblioteca-della-liberta/edizione-online.html", "centroeinaudi.it/biblioteca-della-liberta/numero-attuale.html"], "adapter": "biblioteca-della-liberta", "params": {}, "notes": "Rivista del Centro Einaudi, ad accesso aperto. Dal 2025 pubblica articolo per articolo ('Online First Articles', DOI 10.23827/BDL_<anno>_<n>): questi vengono letti dalla lista Online First, con DOI, abstract e PDF dalla pagina dell'articolo. I fascicoli precedenti (2011-2025, n. 200-242) vengono letti dalle pagine dei fascicoli (titolo, autori, pagina iniziale, PDF). I fascicoli 2009-2010 del sito non hanno PDF; l'archivio 1987-2008 è una pagina a parte non inclusa. Escluse le note biografiche."},
		{"match": ["teseo.unitn.it/biolaw"], "adapter": "ojs", "params": {"base": "https://teseo.unitn.it/biolaw", "excludeSets": ["INDICE"]}, "notes": "BioLaw Journal – Rivista di BioDiritto (Università di Trento, OJS). Scarica tutti i contributi dal 2014 via OAI-PMH con PDF: saggi, focus, forum, note a sentenza, sezioni monografiche; esclusi gli indici dei fascicoli. Metadati: titolo, autori, data, numero, pagine iniziali, DOI."},
		{"match": ["digitalcommons.law.buffalo.edu/buffalolawreview"], "adapter": "oai", "params": {"endpoint": "https://digitalcommons.law.buffalo.edu/do/oai/", "set": "publication:buffalolawreview", "skipPattern": "^(cover( page)?( and| &)?( front matter| editorial board)?|front matter|back matter|table of contents?|masthead|editorial board|publisher( info)?|copyright|recent and forthcoming|dedication|full issue)(\\s*[-–:].*)?$"}, "notes": "Buffalo Law Review (University at Buffalo) su Digital Commons (bepress), open access: elenco da OAI-PMH con titolo, autori, data, volume e fascicolo. Esclusi copertine, front matter, masthead, editorial board, indici (Table of Contents), pagine di copyright/publisher. I PDF sono dietro Cloudflare: in Zotero vengono scaricati tramite il browser nascosto (fallback); se il download fallisce l'elemento viene creato senza allegato."},
		{"match": ["calumet-review.com"], "adapter": "wordpress", "params": {"base": "https://calumet-review.com", "restRoute": true, "query": {"categories": "18"}}, "notes": "Sito bilingue (Polylang): ogni saggio esiste in versione italiana e inglese, con PDF distinti; si scarica solo la versione della categoria 'Issues' (lato inglese), per evitare doppioni. La REST API funziona solo via ?rest_route= (wp-json dà 404). Esclusi Observer/News. Autori non disponibili."},
		{"match": ["rivista.camminodiritto.it"], "adapter": "cammino-diritto", "params": {}, "notes": "Rivista online (ASP) con migliaia di contributi, tutti ad accesso aperto come pagina e PDF del singolo articolo. L'elenco completo viene dalla sitemap del sito (circa 4.000 contributi dal 2015), letta dal più recente; titolo completo, autori, data, abstract e PDF dalla pagina dell'articolo. Include contributi scientifici e divulgativi (il sito li distingue solo nel testo della pagina). I fascicoli trimestrali in PDF sono riservati agli iscritti e non vengono usati. Il primo scaricamento completo richiede una pagina per articolo (circa 4.000 richieste); con un anno di partenza recente è molto più breve (circa 270 articoli dal 2025)."},
		{"match": ["cambridge.org/core/journals/canadian-journal-of-law-and-society-la-revue-canadienne-droit-et-societe"], "adapter": "cambridge", "params": {"issn": "0829-3201"}, "notes": "Rivista ibrida (Cambridge University Press) diventata di fatto ad accesso aperto dal 2023-2024: vengono scaricati solo gli articoli con licenza Creative Commons (tutti quelli dal 2024, pochi negli anni precedenti), compresi recensioni in francese e inglese. Metadati completi da Crossref, PDF dalla pagina Cambridge Core. Gli articoli FirstView vengono importati alla prima apparizione, senza volume/fascicolo."},
		{"match": ["ceridap.eu"], "adapter": "wordpress", "params": {"base": "https://ceridap.eu", "requirePdf": false, "pdfFromContent": false, "doiSelector": "a[href^=\"https://doi.org/10.13130/\"]", "pdfUrlTemplate": "https://ceridap.eu/pdf/estratti/Estratto-{doi_}.pdf", "pdfWaitDays": 150}, "notes": "Articoli dal sito (WordPress). Il PDF di ogni articolo è l'estratto /pdf/estratti/Estratto-<DOI>.pdf, con il DOI letto dalla pagina dell'articolo; è disponibile solo alla chiusura del fascicolo (fine trimestre): fino ad allora l'articolo resta in attesa del PDF e viene ricontrollato alle esecuzioni successive (per 150 giorni)."},
		{"match": ["scholarship.kentlaw.iit.edu/cklawreview"], "adapter": "oai", "params": {"endpoint": "https://scholarship.kentlaw.iit.edu/do/oai/", "set": "publication:cklawreview", "skipPattern": "^(cover( page)?( and| &)?( front matter| editorial board)?|front matter|back matter|table of contents?|masthead|editorial board|publisher( info)?|copyright|recent and forthcoming|dedication|full issue)(\\s*[-–:].*)?$"}, "notes": "Chicago-Kent Law Review (IIT Chicago-Kent College of Law) su Digital Commons (bepress), open access: elenco da OAI-PMH con titolo, autori, data, volume e fascicolo. Esclusi copertine, front matter, masthead, editorial board, indici (Table of Contents), pagine di copyright/publisher. I PDF sono dietro Cloudflare: in Zotero vengono scaricati tramite il browser nascosto (fallback); se il download fallisce l'elemento viene creato senza allegato. Numeri in gran parte monografici (simposi)."},
		{"match": ["columbialawreview.org"], "adapter": "columbia-law-review", "params": {}, "notes": "Archivio /content/ (tutti i contributi, più recenti prima: articoli, note, essay, recensioni e pezzi del CLR Forum). Volume e numero dall'elenco ('Vol. 126, No. 4'), anno = 1900 + volume; il PDF è nella pagina dell'articolo. Titoli in maiuscolo sul sito (convertiti). Autori non importati: con le iniziali intermedie ('Nicholas O. Stephanopoulos') lo split nome/cognome del core è errato."},
		{"match": ["apcz.umk.pl/clr", "apcz.umk.pl/clr/issue/view/3136"], "adapter": "comparative-law-review", "params": {"base": "https://apcz.umk.pl/CLR", "excludeSets": ["rev"], "skipPattern": "^(title page|erratum)"}, "notes": "Comparative Law Review dell'Università Nicolaus Copernicus di Toruń (Polonia), piattaforma OJS AUC. Scarica tutti gli articoli dal 2013 (vol. 15) via OAI-PMH con PDF: articoli, studi, note, recensioni, editoriali. Esclusi elenco dei revisori, frontespizio/sommario annuale ed errata. Metadati completi (volume, pagine, DOI). Attenzione: esiste un'omonima rivista italiana (Università di Perugia, comparativelawreview.giurisprudenza.unipg.it) non coperta da questa voce."},
		{"match": ["comparazionedirittocivile.it"], "adapter": "crawl", "params": {"start": ["https://www.comparazionedirittocivile.it/index.php?id=teoria-generale", "https://www.comparazionedirittocivile.it/index.php?id=persone", "https://www.comparazionedirittocivile.it/index.php?id=famiglia", "https://www.comparazionedirittocivile.it/index.php?id=successioni", "https://www.comparazionedirittocivile.it/index.php?id=diritti-reali", "https://www.comparazionedirittocivile.it/index.php?id=obbligazioni-contratti", "https://www.comparazionedirittocivile.it/index.php?id=responsabilita-civile", "https://www.comparazionedirittocivile.it/index.php?id=impresa-societa-mercati-finanziari", "https://www.comparazionedirittocivile.it/index.php?id=ip-nuove-tecnologie", "https://www.comparazionedirittocivile.it/index.php?id=tutela-diritti", "https://www.comparazionedirittocivile.it/index.php?id=note-commenti-rassegne-recensioni", "https://www.comparazionedirittocivile.it/index.php?id=atti-convegni-seminari", "https://www.comparazionedirittocivile.it/index.php?id=osservatori"], "blockClosest": "p", "titleSelector": ".title", "authorsSelector": ".author", "titlePattern": "^(?<date>[A-Za-z]+\\s+\\d{4})\\b", "stopAfterSeen": 100000}, "notes": "Rivista (Edizioni Scientifiche Italiane). Sul sito gli articoli sono elencati per materia; fino a maggio 2019 ogni articolo ha un PDF gratuito sul sito, e questi vengono scaricati (circa 470 articoli 2010-2019, con data mese/anno). Dalla seconda metà del 2019 gli articoli rimandano all'e-shop ESI (estratti PDF, presumibilmente a pagamento) e non vengono scaricati. Esclusi i PDF dei fascicoli interi (archivio volumi 2014-2018)."},
		{"match": ["giurcost.org/studi", "giurcost.org"], "adapter": "consulta-online", "params": {}, "notes": "Rivista di giurisprudenza costituzionale (giurcost.org): la rivista vera e propria è la sezione 'Studi', organizzata in fascicoli (tre l'anno dal 2015, fascicolo unico 2000-2014). Scarica gli studi di ogni fascicolo con titolo, autore, data di pubblicazione e PDF; gli studi più vecchi pubblicati solo in HTML sono salvati come pagina web. Esclusi decisioni della Corte, rubriche, eventi, 'Speciali' e PDF annuali della rivista, indici. Il fascicolo in corso viene riletto a ogni aggiornamento perché cresce nei quattro mesi."},
		{"match": ["cortisupremeesalute.it"], "adapter": "crawl", "params": {"start": "https://www.cortisupremeesalute.it/archivio/", "issueSelector": "a[href*=\"/issue/\"]", "articleSelector": "article.type-article", "linkSelector": "a.list-group-item", "titleSelector": "h4", "authorsSelector": "p.list-group-item-text", "dateFromIssue": false, "landing": true}, "notes": "Archivio fascicoli (/archivio/) → pagina di ogni fascicolo (/issue/...) con l'elenco degli articoli (titolo, autore); la pagina dell'articolo ha i meta citation_* (titolo, data, citation_pdf_url). Il PDF del fascicolo intero non viene scaricato. Il campo numero riporta l'etichetta 'Fascicolo 01-02/2026'."},
		{"match": ["costituzionalismo.it"], "adapter": "wordpress", "params": {"base": "https://www.costituzionalismo.it", "authorsFrom": "yoast"}, "notes": "Tutti i post del sito sono articoli della rivista (fascicoli dal 2003, sezioni saggi/commenti/rubriche), ciascuno con 'Scarica PDF'. Autore dal campo Yoast (con più coautori può comparire solo il primo). La risposta wp-json inizia con un BOM UTF-8, gestito dal decoder."},
		{"match": ["journals.uniurb.it/index.php/cgdv"], "adapter": "ojs", "params": {"base": "https://journals.uniurb.it/index.php/cgdv", "skipPattern": "^copertina"}, "notes": "Rivista del Dipartimento di Giurisprudenza dell'Università di Urbino (OJS, pubblicazione continua). Scarica tutti i contributi dal 2014 via OAI-PMH con PDF: saggi, note e commenti, materiali, numeri speciali; escluse due copertine dei numeri speciali 2015-2016. Metadati: titolo, autori, data, volume, DOI."},
		{"match": ["deiustitia.it"], "adapter": "wordpress", "params": {"base": "https://deiustitia.it", "query": {"categories_exclude": "110,111,112,113,114,115,139,117,258,164"}}, "notes": "Si scaricano i contributi di dottrina (post delle categorie diritto civile/penale/pubblico/internazionale, con un PDF ciascuno). Escluse la 'Rassegna' di giurisprudenza (post che allegano la sentenza e un commento breve), i PDF dei fascicoli interi ('Pubblicazione nr. N'), comunicati e atti di convegno. Autori non disponibili."},
		{"match": ["dirittobancario.it/dialoghi"], "adapter": "wordpress", "params": {"base": "https://www.dirittobancario.it", "query": {"categories": "776,777,778"}, "pdfSelector": "a[href*=\"dirittobancario.it/wp-content/uploads/\"][href$=\".pdf\"]", "requirePdf": false, "htmlToPdf": true}, "notes": "Sezione della rivista dentro dirittobancario.it: solo i post delle categorie Editoriali, Articoli e Note (le sezioni della rivista), non il resto del sito. Il PDF è quello caricato su dirittobancario.it nel testo (i link a PDF esterni sono fonti citate). Gli editoriali non hanno PDF: istantanea della pagina. Le sezioni contengono anche contributi 2019-2021 precedenti alla nascita della rivista (luglio 2021)."},
		{"match": ["dirittiregionali.it"], "adapter": "wordpress", "params": {"base": "https://www.dirittiregionali.it", "query": {"categories_exclude": "1661,28,1438,924,69,31,988,77,1994,2091"}, "authorsFrom": "yoast"}, "notes": "Post con PDF 'documento integrale'; esclusi news, eventi, seminari, bandi, call e i PDF dei fascicoli interi. Autori dal campo Yoast (anche più autori). I vecchi post dell'archivio 2012-2015 senza PDF sono saltati."},
		{"match": ["dirittifondamentali.it"], "adapter": "wordpress", "params": {"base": "https://dirittifondamentali.it", "query": {"categories": "47"}}, "notes": "Vengono scaricati i contributi dei fascicoli della rivista (categoria WordPress 'Fascicoli': saggi, editoriali, numeri monografici), ciascuno con il suo PDF, dal 2012. Non vengono scaricate le sezioni 'Giurisprudenza' (testi di sentenze di Corte costituzionale, Corte EDU, CGUE, Cassazione, TAR, circa 3000 documenti), 'Eventi', 'Attualità' e i comunicati. Metadati: titolo, autori (dal plugin autori del sito), data di pubblicazione online; il numero del fascicolo (es. 3/2026) non viene registrato."},
		{"match": ["dirittodellosport.eu"], "adapter": "wordpress", "params": {"base": "https://dirittodellosport.eu", "landing": true, "query": {"categories_exclude": "36,1"}}, "notes": "Rivista semestrale (Bononia University Press), dal 2020: vengono scaricati tutti i contributi (saggi, note, Osservatorio sulla giurisprudenza sportiva) con il PDF, letto dalla pagina dell'articolo. Esclusi gli avvisi di eventi. Metadati: titolo e data di pubblicazione online; autori, DOI e fascicolo sono visibili sul sito ma non in forma leggibile automaticamente e non vengono registrati. Qualche contributo (es. 'La torcia olimpica…', 7/2026) non ha ancora il PDF sul sito: viene creato senza allegato."},
		{"match": ["dirittoesalute.org"], "adapter": "wordpress", "params": {"base": "https://www.dirittoesalute.org", "authorSelector": "body > p:first-child strong"}, "notes": "Rivista di sanità e responsabilità medica, 3 fascicoli l'anno dal 2017: vengono scaricati tutti i contributi (saggi, commenti, recensioni), ciascuno con il suo PDF. Metadati: titolo, autori (dalla riga 'di Nome Cognome' in testa all'articolo), data di pubblicazione online; il numero del fascicolo non viene registrato."},
		{"match": ["giureta.unipa.it"], "adapter": "diritto-economia-trasporti-ambiente", "params": {}, "notes": "Rivista GIURETA dell'Università di Palermo, ad accesso aperto (CC BY-NC-ND), pubblicata a flusso continuo in un volume annuale più supplementi. Vengono scaricati i PDF dei singoli articoli dal 2009 in poi (i volumi 2003-2008 hanno articoli solo in HTML e non vengono scaricati). Titolo e autore sono ricavati dal testo del link (pagine prodotte da un programma di videoscrittura): in rari casi la separazione autore/titolo può essere imprecisa. Data = anno del volume (o data nel nome del file, per alcune annate)."},
		{"match": ["rivistadga.it"], "adapter": "wordpress", "params": {"base": "https://www.rivistadga.it", "landing": true, "query": {"categories_exclude": "1,15,99,101,103,105,755,758"}}, "notes": "Rivista bimestrale online (Rivista DGA). Vengono scaricati i contributi pubblicati come singoli articoli dal novembre 2015: dottrina ('Contributi'), note a sentenza ('Note'), rassegne e recensioni, con il PDF letto dalla pagina dell'articolo. Esclusi i massimari di giurisprudenza, i post 'Numero X – AAAA' con il fascicolo intero e l'archivio 2008-2015, disponibile solo come PDF dei fascicoli interi. Metadati: titolo e data di pubblicazione online; autore e numero del fascicolo compaiono sul sito ma non vengono registrati."},
		{"match": ["dirittoepoliticadeitrasporti.it"], "adapter": "diritto-politica-trasporti", "params": {}, "notes": "Vengono scaricati i contributi della rivista pubblicati nelle sezioni 'Articoli e saggi', 'Note a sentenza' e 'Rassegne, commenti e recensioni', ciascuno con il suo PDF, dal 2018. Ogni contributo è pubblicato sul sito due volte (pagina italiana e inglese con lo stesso PDF): viene importato una sola volta, con la pagina italiana. Esclusi i fascicoli interi e le sezioni documentali (casi e questioni, giurisprudenza, normativa, materiali, studi e ricerche, novità bibliografiche). Metadati: titolo, autori (dal titolo 'Autore, Titolo'), anno e numero del fascicolo (es. I/2026) e pagine, dalla riga di citazione dell'articolo."},
		{"match": ["serena.sharepress.it/dperonline", "serena.unina.it/index.php/dperonline"], "adapter": "ojs", "params": {"base": "https://serena.sharepress.it/dperonline", "excludeSets": ["FC", "CFP", "IE", "ORI"]}, "notes": "Rivista dell'Università di Napoli Federico II, ora su serena.sharepress.it (il vecchio indirizzo serena.unina.it reindirizza qui). Scarica via OAI-PMH con PDF saggi, articoli, note, osservatori, materiali e sezioni monografiche dal 2019 (con alcuni contributi più vecchi). Esclusi fascicoli completi, call for papers e la sezione 'In evidenza' (locandine di eventi e annunci). Metadati: titolo, autori, data, volume, numero, DOI."},
		{"match": ["journals.uniurb.it/index.php/dsl"], "adapter": "ojs", "params": {"base": "https://journals.uniurb.it/index.php/dsl"}, "notes": "Rivista dell'Osservatorio Olympus (Università di Urbino, OJS). Scarica tutti i saggi e le note dal 2016 via OAI-PMH con PDF. Metadati completi: titolo, autori, data, numero, pagine, DOI."},
		{"match": ["journals.francoangeli.it/index.php/ecagoa", "economiaagroalimentare.it"], "adapter": "ojs", "params": {"base": "https://journals.francoangeli.it/index.php/ecagoa", "mode": "archive"}, "notes": "Il sito della rivista (economiaagroalimentare.it, Jimdo) rimanda per gli articoli alla piattaforma open access di FrancoAngeli (OJS, journals.francoangeli.it/index.php/ecagoa), da cui vengono scaricati articoli e PDF dei fascicoli dal 2020 (vol. 22) in poi, compresi gli 'Early View' e i numeri speciali. I fascicoli 1999-2019 sono solo sul sito commerciale di FrancoAngeli (DOI 10.3280/ECAG…, a pagamento) e non vengono scaricati. Gli articoli in Early View possono essere privi di data finché non entrano in un fascicolo."},
		{"match": ["riviste.paviauniversitypress.it/index.php/ea"], "adapter": "ojs", "params": {"base": "http://riviste.paviauniversitypress.it/index.php/ea", "excludeSets": ["GDLAT", "cfp", "IE", "bpa2023", "BPA", "wp2023"], "skipPattern": "reviewers"}, "notes": "Rivista di economia aziendale (Pavia University Press, OJS 2). Scarica via OAI-PMH con PDF tutti gli articoli dal 2010 (refereed papers, working papers, principles, special issue, sezione didattica). Esclusi linee guida per gli autori, call for papers, annunci, premi e gli elenchi annuali dei revisori. Metadati completi: titolo, autori, data, volume, numero, pagine, DOI."},
		{"match": ["economiaepolitica.it"], "adapter": "wordpress", "params": {"base": "https://www.economiaepolitica.it", "query": {"categories[terms]": "2751", "categories[include_children]": "true"}, "pdfFromContent": false, "landingPdfSelector": ".entry-console a[href*=\"/_pdfs/\"]"}, "notes": "Rivista online di critica della politica economica, con due fascicoli semestrali l'anno dal 2008. Vengono scaricati i contributi assegnati a un fascicolo (categoria 'Pubblicazioni', circa 890 dal 2008), con il PDF generato dal sito (pulsante 'Scarica pdf' della pagina dell'articolo). Esclusi le pagine 'chi siamo', la rassegna stampa, i video e le segnalazioni. I PDF di documenti esterni citati nel testo (Banca d'Inghilterra, ecc.) non vengono presi. Metadati: titolo e data; autore e numero del fascicolo non vengono registrati."},
		{"match": ["dirittoantidiscriminatorio.it"], "adapter": "crawl", "params": {"start": "https://www.dirittoantidiscriminatorio.it/rivista/", "articleSelector": ".single-category", "linkSelector": "a[href*=\"/rivista/\"]", "titleSelector": "a:last-child", "titlePattern": "(?<date>\\d{1,2} [A-Za-zà-ù]+ \\d{4})", "nextSelector": "a.next", "preferListMeta": true, "landingPdfSelector": "main a[href$=\".pdf\"]"}, "notes": "EQUAL - Rivista di diritto antidiscriminatorio: vengono scaricati i contributi della sezione 'Rivista' del sito (saggi, giurisprudenza, Dialogues), ciascuno con il suo PDF letto dalla pagina dell'articolo; l'archivio online della rivista sul sito parte da maggio 2024. Esclusi i post del blog (attualità, letture, segnalazioni) e il PDF del fascicolo intero. Metadati: titolo e data; autori e numero del fascicolo non vengono registrati."},
		{"match": ["jelt.padovauniversitypress.it"], "adapter": "ethics-legal-technologies", "params": {}, "notes": "Rivista semestrale di Padova University Press (Drupal 10). Si legge l'elenco dei fascicoli e l'indice di ciascuno; dalle pagine articolo si prendono i metadati completi (citation_*) e il PDF. Scaricati tutti i fascicoli dal 2019 (vol. 1)."},
		{"match": ["rivistaeticapubblica.it/index.php/eticapubblica"], "adapter": "ojs", "params": {"base": "https://www.rivistaeticapubblica.it/index.php/eticapubblica", "skipPattern": "^(indice|index|autori|gli autori)$"}, "notes": "Etica Pubblica. Studi su legalità e partecipazione (OJS, dal 2022). Scarica via OAI-PMH con PDF saggi, note e commenti, recensioni ('Letti e riletti'), forum e le presentazioni dei fascicoli ('In questo numero'); esclusi indici ed elenchi degli autori. Metadati: titolo, autori, data, volume, numero, DOI."},
		{"match": ["rivista.eurojus.it"], "adapter": "wordpress", "params": {"base": "https://rivista.eurojus.it"}, "notes": "Rivista di diritto dell'Unione europea: vengono scaricati i contributi pubblicati sul sito (articoli, interventi, relazioni, note, segnalazioni, recensioni) che hanno un PDF, circa 100 l'anno, dal 2014. I contributi più brevi pubblicati solo in HTML (circa un quarto, soprattutto segnalazioni 2014-2019) non vengono scaricati. Metadati: titolo e data di pubblicazione online; gli autori non sono disponibili in forma strutturata e non vengono registrati."},
		{"match": ["cambridge.org/core/journals/european-constitutional-law-review"], "adapter": "cambridge", "params": {"issn": "1574-0196"}, "notes": "Rivista Cambridge ad accesso aperto per i nuovi articoli (le annate precedenti sono in gran parte in abbonamento): vengono scaricati solo gli articoli con licenza Creative Commons. Copertine/front matter e alcuni editoriali senza licenza CC vengono saltati. Metadati da Crossref, PDF dalla pagina Cambridge Core; gli articoli FirstView vengono importati senza volume/fascicolo."},
		{"match": ["cambridge.org/core/journals/european-law-open"], "adapter": "cambridge", "params": {"issn": "2752-6135"}, "notes": "Rivista Cambridge interamente ad accesso aperto (dal 2022). Vengono scaricati tutti gli articoli con metadati da Crossref e PDF dalla pagina Cambridge Core; gli articoli FirstView vengono importati alla prima apparizione, senza volume/fascicolo."},
		{"match": ["ejlt.org/index.php/ejlt", "ejlt.org"], "adapter": "ojs", "params": {"base": "https://ejlt.org/index.php/ejlt"}, "notes": "European Journal of Law and Technology (BILETA, OJS). Scarica via OAI-PMH tutti i contributi dal 2010 (articoli, commenti, editoriali, recensioni, atti BILETA). Metadati: titolo, autori, data, volume, numero. Circa 60 contributi più vecchi (soprattutto recensioni ed editoriali 2010-2014) esistono solo in HTML: vengono importati senza PDF."},
		{"match": ["sites.eui.eu/european-journal-of-legal-studies", "ejls.eui.eu"], "adapter": "european-legal-studies", "params": {}, "notes": "La rivista (EUI) si è trasferita da ejls.eui.eu a sites.eui.eu/european-journal-of-legal-studies; tutti gli articoli (editoriali, articoli, New Voices, recensioni, numeri speciali) sono depositati ad accesso aperto nel repository dell'EUI Cadmus, da cui vengono scaricati metadati (autori, data di pubblicazione online, volume, fascicolo, pagine, DOI 10.2924/EJLS…, abstract) e PDF. I titoli seguono lo stile del repository (minuscole, 'titolo: sottotitolo'). Il link dell'articolo in Zotero è l'handle (hdl.handle.net/1814/…)."},
		{"match": ["europeanpapers.eu"], "adapter": "european-papers", "params": {}, "notes": "Vengono scaricati gli articoli dell'e-Journal (tre fascicoli l'anno, pubblicati articolo per articolo; incluse le sezioni speciali), dall'elenco /category/e-journal, con metadati completi dalla pagina dell'articolo (DOI, volume, fascicolo, pagine, abstract, parole chiave) e PDF ad accesso aperto (CC BY-NC-ND). Non vengono scaricati i fascicoli completi in PDF, gli indici e le copertine. Lo 'European Forum' (2016-2024) è chiuso e non ha un elenco proprio: sono inclusi solo gli eventuali contributi classificati come e-Journal. Nota: per alcuni articoli il sito indica nei metadati un fascicolo diverso da quello del nome del PDF (es. 11(2) per un PDF 'EP_eJ_2026_3'): viene usato il dato dei metadati."},
		{"match": ["universitypress.unisob.na.it/ojs/index.php/ejplt"], "adapter": "crawl", "params": {"start": ["https://universitypress.unisob.na.it/ojs/index.php/ejplt/issue/archive", "https://universitypress.unisob.na.it/ojs/index.php/ejplt/issue/archive?issuesPage=2"], "issueSelector": "h4 a[href*=\"/issue/view/\"]", "issuePattern": "/issue/view/(?!155$)\\d+$", "articleSelector": "table.tocArticle", "titleSelector": ".tocTitle", "linkSelector": ".tocTitle a", "pdfSelector": "a.file", "landing": true, "issueFromLabel": false}, "notes": "European Journal of Privacy Law & Technologies (Università Suor Orsola Benincasa, OJS 2). Scarica tutti i fascicoli (ordinari e speciali, dal 2018) dall'archivio con PDF: articoli, commenti, casi, focus, news. Esclusa la sezione 'Observatory' (solo HTML). Metadati dalla pagina dell'articolo: titolo (spesso bilingue 'inglese | italiano'), autori, data. Volume e numero indicati dal sito come 0."},
		{"match": ["erdalreview.eu"], "adapter": "european-review-digital-administration", "params": {}, "notes": "Rivista semestrale (Aracne editrice), tutti i fascicoli dal 2020 con PDF gratuiti per singolo articolo (/free-download/). Dalla pagina del fascicolo vengono letti autori, titolo, DOI (10.53136/…), pagine, volume e numero; la data è solo l'anno. Esclusi il fascicolo completo e l'indice; i titoli di sezione (Studia Varia, Book Review…) non sono articoli e vengono ignorati."},
		{"match": ["cambridge.org/core/journals/european-journal-of-risk-regulation"], "adapter": "cambridge", "params": {"issn": "1867-299X"}, "notes": "Rivista ibrida Cambridge: vengono scaricati solo gli articoli ad accesso aperto (licenza Creative Commons secondo Crossref), che dal 2021 sono quasi tutti. Metadati da Crossref, PDF dalla pagina Cambridge Core; gli articoli FirstView (la maggior parte, la rivista pubblica in continuo) vengono importati senza volume/fascicolo."},
		{"match": ["eujournal.org/index.php/esj"], "adapter": "ojs", "params": {"base": "https://eujournal.org/index.php/esj", "excludeSets": ["Preprints"]}, "notes": "European Scientific Journal (European Scientific Institute, OJS): rivista multidisciplinare di grandi dimensioni (scienze sociali, umane, naturali e mediche; circa 15.000 articoli dal 2012, oltre 1.000 l'anno). Scarica via OAI-PMH tutti gli articoli con PDF, esclusi i preprint (ESI Preprints). Non è possibile limitarsi alle scienze sociali: il sito non distingue le aree nei dati OAI. Si consiglia di impostare un anno di partenza."},
		{"match": ["federalismi.it"], "adapter": "federalismi-it", "params": {}, "notes": "Vengono scaricati i fascicoli numerati della rivista (pagina 'Numeri precedenti'): editoriale e articoli di dottrina di ogni fascicolo, con PDF (gratuiti, senza login). Non vengono scaricati i materiali delle sezioni normativa/giurisprudenza/documentazione, i numeri 'Focus'/Osservatori (che condividono la numerazione) né i digest periodici 'Osservatorio del …'. Per i fascicoli 2003-2007 la pagina del fascicolo elenca solo l'editoriale: degli anni più vecchi viene quindi scaricato solo quello. Il fascicolo più recente viene ricontrollato a ogni esecuzione."},
		{"match": ["fqpjournal.com"], "adapter": "filosofia-e-questioni-pubbliche", "params": {}, "notes": "Philosophy and Public Issues (Giappichelli, CC BY-NC-SA): vengono scaricati gli articoli dei fascicoli pubblicati sulla nuova piattaforma (dal 2024, due fascicoli l'anno), con titolo, autori, data e numero del fascicolo, DOI (10.17473/2240-7987-…) e PDF del singolo articolo. I fascicoli 2011-2021 sono disponibili solo come PDF dell'intero fascicolo (sezione 'Issues earlier than 2024') e non vengono scaricati; i fascicoli 2022-2023 non risultano online sul sito."},
		{"match": ["ecollections.law.fiu.edu/lawreview"], "adapter": "oai", "params": {"endpoint": "https://ecollections.law.fiu.edu/do/oai/", "set": "publication:lawreview", "skipPattern": "^(cover( page)?( and| &)?( front matter| editorial board)?|front matter|back matter|table of contents?|masthead|editorial board|publisher( info)?|copyright|recent and forthcoming|dedication|full issue)(\\s*[-–:].*)?$"}, "notes": "FIU Law Review (Florida International University) su Digital Commons (bepress), open access: elenco da OAI-PMH con titolo, autori, data, volume e fascicolo. Esclusi copertine, front matter, masthead, editorial board, indici (Table of Contents), pagine di copyright/publisher. I PDF sono dietro Cloudflare: in Zotero vengono scaricati tramite il browser nascosto (fallback); se il download fallisce l'elemento viene creato senza allegato. I DOI (10.25148/lawrev…) sono presi da OAI."},
		{"match": ["forumcostituzionale.it/wordpress", "forumcostituzionale.it"], "adapter": "wordpress", "params": {"base": "https://www.forumcostituzionale.it/wordpress", "restRoute": true, "query": {"categories_exclude": "5,8,15,21,29,30,39,41,48,54,200,355,406,407", "after": "2018-01-02T00:00:00"}, "titlePattern": "^(?<title>.+?)\\s+[–—-]\\s+(?:[A-ZÀ-Ý]\\.\\s?)+[^–—]{2,80}$"}, "notes": "Vengono scaricati i contributi pubblicati dal 2018 come singoli articoli (paper, note a sentenza, recensioni, editoriali, atti di convegno), ciascuno con il suo PDF. Esclusi gli annunci dei fascicoli con il PDF del fascicolo intero, gli avvisi, le inserzioni e le rubriche periodiche (Monitore della giurisprudenza costituzionale, Bollettino delle questioni pendenti, Settimana delle istituzioni). I materiali 1999-2017 sono pubblicati come pagine-indice con decine di PDF e non vengono scaricati. Metadati: titolo (senza il nome dell'autore in coda) e data di pubblicazione online; autori e numero del fascicolo non vengono registrati."},
		{"match": ["fsjeurostudies.eu"], "adapter": "freedom-security-justice", "params": {}, "notes": "Freedom, Security & Justice: European Legal Studies (Università di Salerno, CC BY-SA): tre fascicoli l'anno dal 2017, tutti con PDF gratuiti per articolo. Vengono importati titolo, anno e numero del fascicolo; gli autori non sono disponibili in forma strutturata (compaiono solo come testo sotto il titolo) e restano da completare. Vengono importati anche editoriali, presentazioni dei focus e postfazioni (sono PDF autonomi della rivista)."},
		{"match": ["journals.law.harvard.edu/ilj"], "adapter": "harvard-international-law-journal", "params": {}, "notes": "Vengono scaricati gli articoli dei fascicoli a stampa (volumi 54-67, 2013-2026, dalle pagine 'Volume N, Issue M' che elencano i PDF) e l'archivio per articolo 2011-2013; esclusi front matter, masthead e indici. Non vengono scaricati i contributi online (HILJ Online: essays, digest, simposi), pubblicati solo in HTML. Metadati: titolo, autori (dalla riga 'By …'), volume, fascicolo e anno (volume + 1959)."},
		{"match": ["harvardlawreview.org"], "adapter": "harvard-law-review", "params": {}, "notes": "Vengono scaricati tutti i contributi dei fascicoli a stampa (articoli, note, recent cases, Supreme Court leading cases, recensioni, commenti) e del Forum online, ciascuno con il suo PDF, letto con gli autori dalla pagina dell'articolo. Non viene scaricato il blog. Metadati: titolo, autori, data, volume, fascicolo e prima pagina (dal nome del PDF, es. 139 Harv. L. Rev. 1918); le note degli studenti sono anonime. L'archivio online è sistematico da circa il vol. 125 (2011), con alcuni classici più vecchi."},
		{"match": ["repository.uclawsf.edu/hastings_international_comparative_law_review"], "adapter": "oai", "params": {"endpoint": "https://repository.uclawsf.edu/do/oai/", "set": "publication:hastings_international_comparative_law_review", "skipPattern": "^(cover( page)?( and| &)?( front matter| editorial board)?|front matter|back matter|table of contents?|masthead|editorial board|publisher( info)?|copyright|recent and forthcoming|dedication|full issue)(\\s*[-–:].*)?$"}, "notes": "UC Law SF International Law Review (già Hastings International and Comparative Law Review) su Digital Commons (bepress), open access: elenco da OAI-PMH con titolo, autori, data, volume e fascicolo. Esclusi copertine, front matter, masthead, editorial board, indici (Table of Contents), pagine di copyright/publisher. I PDF sono dietro Cloudflare: in Zotero vengono scaricati tramite il browser nascosto (fallback); se il download fallisce l'elemento viene creato senza allegato. La rivista ha cambiato nome dopo la ridenominazione di UC Hastings in UC Law SF; l'indirizzo della collezione è rimasto lo stesso."},
		{"match": ["repository.uclawsf.edu/hastings_law_journal"], "adapter": "oai", "params": {"endpoint": "https://repository.uclawsf.edu/do/oai/", "set": "publication:hastings_law_journal", "skipPattern": "^(cover( page)?( and| &)?( front matter| editorial board)?|front matter|back matter|table of contents?|masthead|editorial board|publisher( info)?|copyright|recent and forthcoming|dedication|full issue)(\\s*[-–:].*)?$"}, "notes": "UC Law Journal (già Hastings Law Journal, UC Law SF) su Digital Commons (bepress), open access: elenco da OAI-PMH con titolo, autori, data, volume e fascicolo. Esclusi copertine, front matter, masthead, editorial board, indici (Table of Contents), pagine di copyright/publisher. I PDF sono dietro Cloudflare: in Zotero vengono scaricati tramite il browser nascosto (fallback); se il download fallisce l'elemento viene creato senza allegato. La rivista ha cambiato nome in UC Law Journal; l'indirizzo della collezione è rimasto lo stesso. Sono escluse anche le pagine \"Recent and Forthcoming\"."},
		{"match": ["i-lex.unibo.it", "i-lex.it"], "adapter": "ojs", "params": {"base": "https://i-lex.unibo.it"}, "notes": "Dal 2022 (vol. 15, 'terza serie') i-lex è pubblicata su OJS dell'Università di Bologna (i-lex.unibo.it): vengono scaricati tutti gli articoli di questa serie con metadati completi (autori, data, volume, fascicolo, pagine, DOI 10.6092/issn.1825-1927/…) e PDF. Il vecchio sito www.i-lex.it (Joomla) resta come archivio della prima serie (voll. 1-10, 2004-2016 circa, PDF) e della seconda serie (voll. 11-14, 2018-2021, articoli in HTML) e non viene scaricato."},
		{"match": ["ildirittoamministrativo.it"], "adapter": "crawl", "params": {"start": ["https://www.ildirittoamministrativo.it/studi", "https://www.ildirittoamministrativo.it/temi-dibattiti"], "articleSelector": "form#contact h4", "titleSelector": "a", "linkSelector": "a[href]", "titlePattern": "(?<date>\\d{2}/\\d{2}/\\d{4})", "htmlToPdf": true}, "notes": "Rivista online (flusso continuo, senza fascicoli). Vengono importati i contributi delle sezioni 'Studi' e 'Temi e dibattiti' come pagine web con istantanea (snapshot) del testo integrale, che è leggibile liberamente; il PDF invece richiede la registrazione (gratuita) al sito e non viene scaricato. Gli autori non vengono letti (compaiono sotto il titolo nell'elenco) e vanno completati a mano se servono. Limite importante: gli elenchi mostrano senza login solo i 7 contributi più recenti per sezione (le pagine successive si ottengono solo inviando un modulo, cosa che il plugin non fa): conviene eseguire la raccolta almeno ogni due-tre settimane. Non vengono importate le note di giurisprudenza, le 'Ultimissime' e le novità legislative."},
		{"match": ["ildirittodelleconomia.it"], "adapter": "wordpress", "params": {"base": "https://www.ildirittodelleconomia.it", "titlePattern": "^(?<authors>[^–]{3,150}?)\\s+–\\s+(?<title>.+)$"}, "notes": "Vengono scaricati tutti gli articoli pubblicati sul sito (anticipazioni e fascicoli, 3 l'anno), ciascuno con il suo PDF, dal 2018 (n. 95). Metadati: titolo, autori (dal titolo 'Autore – Titolo'), data di pubblicazione online; il numero del fascicolo non viene registrato. I fascicoli precedenti al 2018 non sono sul sito."},
		{"match": ["thefederalist.eu", "thefederalist.eu/site"], "adapter": "crawl", "params": {"start": "https://www.thefederalist.eu/site/index.php/it/archivio", "issueSelector": "a[href*=\"/it/indice-it/\"]", "articleSelector": ".com-content-article__body td p", "linkSelector": "a[href*=\"/site/index.php/it/\"]", "titleSelector": "a[href*=\"/site/index.php/it/\"]", "authorsSelector": "em", "issueFromLabel": false, "contentSelector": ".com-content-article__body", "htmlToPdf": true}, "notes": "Rivista politica fondata nel 1959 (Joomla), pubblicata in italiano, inglese e francese: si scarica solo l'edizione italiana. Gli articoli sono pagine web senza PDF: il plugin salva l'istantanea della pagina (snapshot). Si parte dagli indici annuali (Archivio → 'Indice dell'anno'), dal più recente; la data è l'anno. Gli editoriali sono firmati 'Il Federalista'."},
		{"match": ["rivistaimpresasociale.it"], "adapter": "crawl", "params": {"start": "https://www.rivistaimpresasociale.it/rivista/archivio", "issueSelector": ".grid > a[href*=\"/rivista/numero/rivista-num-\"]", "articleSelector": ".article-list_item", "linkSelector": "a.article-list_item_title", "titleSelector": "a.article-list_item_title", "authorsSelector": ".article-list_item_author a", "issueFromLabel": false, "landing": true, "skipPattern": "^Cosa trovate in "}, "notes": "Rivista trimestrale di Iris Network (applicazione web su misura, PDF su Amazon S3). Si legge l'archivio dei fascicoli e l'elenco articoli di ciascuno; dalla pagina articolo si prende il PDF e, per gli articoli recenti, i metadati citation_* (DOI 10.7425/IS…, pagine, fascicolo). Esclusa la nota introduttiva 'Cosa trovate in…'. Non viene scaricata la sezione 'Forum' del sito (articoli divulgativi)."},
		{"match": ["jipitec.eu/jipitec", "jipitec.eu"], "adapter": "ojs", "params": {"base": "https://www.jipitec.eu/jipitec"}, "notes": "JIPITEC (OJS, dal 2010). Scarica via OAI-PMH con PDF tutti i contributi: articoli, editoriali, recensioni, decisioni commentate, report, dichiarazioni e documenti (es. European Copyright Society). Metadati: titolo, autori, data, volume, numero."},
		{"match": ["en.ilr-rit.org"], "adapter": "janeway", "params": {"base": "https://en.ilr-rit.org", "browser": true}, "notes": "Dal 2025 la International Labour Review (ILO) è una rivista diamond open access pubblicata su piattaforma Janeway (Open Library of Humanities), edizione inglese su en.ilr-rit.org. I metadati (titolo, autori, data, volume/numero, DOI, abstract) arrivano dall'interfaccia OAI-PMH, che non è protetta; le pagine articolo e i PDF sono dietro un controllo anti-bot (Anubis, 'Making sure you're not a bot'), per cui il plugin scarica i PDF tramite il browser nascosto di Zotero. Le annate 2008-2024 sono su Wiley (non open access) e non vengono scaricate; sulla piattaforma ci sono anche alcuni articoli 2002-2012 ripubblicati."},
		{"match": ["regione.emilia-romagna.it/idf"], "adapter": "istituzioni-del-federalismo", "params": {"htmlToPdf": true}, "notes": "Rivista della Regione Emilia-Romagna (sito Plone 6/Volto). Si usa l'API REST del sito (numeri → anni → fascicoli). Fino al 2024 ogni articolo è un PDF (titolo 'Titolo / Autori', pagine dal nome del file); dal 2025 gli articoli sono pubblicati solo come pagine web (esiste solo il PDF del fascicolo completo): il plugin ne salva l'istantanea (snapshot). Numeri completi e indici non vengono scaricati. Sono inclusi i 'Quaderni' della rivista."},
		{"match": ["illej.unibo.it"], "adapter": "ojs", "params": {"base": "https://illej.unibo.it", "excludeSets": ["ERR"]}, "notes": "Italian Labour Law e-Journal (Università di Bologna, OJS). Scarica via OAI-PMH con PDF i contributi pubblicati sulla piattaforma OJS (dal vol. 12, 2019): editoriali, sezioni tematiche, miscellanea, rapporti nazionali, recensioni; esclusi gli errata. Metadati completi (volume, numero, pagine, DOI). I volumi precedenti al 2019 non sono sulla piattaforma OJS."},
		{"match": ["ipof.it"], "adapter": "wordpress", "params": {"base": "https://www.ipof.it", "query": {"categories_exclude": "51,96"}}, "notes": "Un post WordPress per articolo (categoria = fascicolo, es. 'numero-1-2026') con abstract e link 'Scarica il contributo' al PDF. Vengono esclusi i post delle categorie Newsletter e Call. Metadati: titolo e data di pubblicazione del post; autori e numero del fascicolo non sono disponibili in forma strutturata (gli autori sono nel PDF)."},
		{"match": ["ijpl.eu"], "adapter": "crawl", "params": {"start": "https://www.ijpl.eu/archive/", "issueSelector": "a[href*=\"/archive/archive-\"]", "issuePattern": "/archive-\\d{4}/?$", "articleSelector": ".elementor-widget-icon-box", "titleSelector": ".elementor-icon-box-title", "authorsSelector": ".elementor-icon-box-description", "pdfSelector": ".elementor-icon-box-title a[href$=\".pdf\"]", "skipPattern": "^(IJPL\\b|table of|list of|index)", "issueFromLabel": false}, "notes": "Scarica i PDF di tutti gli articoli dall'archivio per anno (pagine /archive/archive-AAAA/, dal 2009). Metadati: titolo, autori (dalla riga sotto il titolo; in rari editoriali contiene un sottotitolo) e anno; numero e volume del fascicolo non sono ricavati. I PDF del fascicolo completo e gli indici (Table of cases, List of…) sono esclusi. I fascicoli recenti sono anche pubblicati come post HTML, che vengono ignorati (stessi PDF)."},
		{"match": ["rivistaitalianadiinformaticaediritto.it/index.php/riid", "rivistaitalianadiinformaticaediritto.it"], "adapter": "ojs", "params": {"base": "https://www.rivistaitalianadiinformaticaediritto.it/index.php/RIID", "excludeSets": ["RIID:IC"]}, "notes": "Rivista open access del CNR-IGSG (OJS): tutti i contributi dal 2019 (studi, sezioni monografiche, note, recensioni, osservatori) con PDF e metadati da OAI-PMH; esclusi gli indici cumulativi."},
		{"match": ["rivistaitalianadipublicmanagement.it"], "adapter": "crawl", "params": {"start": "https://www.rivistaitalianadipublicmanagement.it/01-2018/", "issueSelector": "li.menu-item-object-page > a", "issuePattern": "/\\d\\d-20\\d\\d(_\\d+)?/?$", "articleSelector": ".post-item", "titleSelector": "h2.entry-title a", "linkSelector": "h2.entry-title a", "authorsSelector": ".post-excerpt b", "titlePattern": "^\\s*(?<date>\\p{L}+ \\d{1,2}, \\d{4})", "issueFromLabel": false, "landing": true, "skipPattern": "(^i colloquia di ripm|^estratto del bando|^call for papers|RIPM\\s*[–-]\\s*Vol\\.?\\s*\\d+\\s*[–-]\\s*nn?\\.)"}, "notes": "Rivista semestrale ad accesso aperto (dal 2018), bilingue: ogni articolo ha un post italiano e uno inglese con lo stesso PDF. Vengono letti i fascicoli dal menu (pagine 'Vol N n.X / anno' e 'Ultimo numero'), solo nella versione italiana, e per ogni articolo la sua pagina, da cui si prende il PDF. Esclusi call for papers, bandi, eventi e pagine 'Rete/Network'. Autori dall'indice del fascicolo quando indicati in grassetto; data = data di pubblicazione online dell'articolo (il volume 8, anno 2025, è uscito nel settembre 2026); volume e numero non vengono compilati."},
		{"match": ["ius-publicum.it/fascicoli"], "adapter": "ius-publicum", "params": {}, "notes": "Tutti i fascicoli (dal 2011) sono elencati in un'unica pagina /fascicoli/ (un riquadro a fisarmonica per fascicolo): vengono scaricati i PDF di articoli e report, con titolo, autori (da 'Autore - Titolo'), anno e numero del fascicolo. Esclusi i PDF 'Fascicolo completo' e gli indici. Per i report scritti 'a. ITA: Autore, Titolo' gli autori restano nel titolo. Molti contributi sono presenti in più lingue: ogni versione è un PDF distinto e diventa un item distinto."},
		{"match": ["judicium.it"], "adapter": "wordpress", "params": {"base": "https://www.judicium.it", "query": {"categories": "60"}, "requirePdf": false, "landingPdfSelector": "#pdf-registered a[href], ul[id^=\"pdf\"] a[href$=\".pdf\"]", "htmlToPdf": true}, "notes": "Viene scaricata solo la sezione online gratuita 'Aggiornamenti' (saggi, opinioni, note a sentenza pubblicati sul sito, circa 140 l'anno). La rivista cartacea (categoria 'Rivista') mostra ai non abbonati solo l'abstract e non viene scaricata. Dal 2023-2024 circa ogni contributo ha il PDF ('Scarica l'articolo in pdf'); i contributi più vecchi sono solo in HTML e vengono salvati come pagina web (snapshot). Metadati: titolo, autore (dalla pagina), data di pubblicazione online."},
		{"match": ["labourlaw.unibo.it"], "adapter": "ojs", "params": {"base": "https://labourlaw.unibo.it", "mode": "archive"}, "notes": "Rivista open access dell'Università di Bologna (OJS senza index.php). Si scorre l'archivio dei fascicoli dal più recente; i metadati (autori, data, volume, fascicolo, pagine, DOI) vengono dalla pagina di ogni articolo. Possono entrare anche le rare errata corrige."},
		{"match": ["ojs.unito.it/index.php/jlmi"], "adapter": "ojs", "params": {"base": "https://ojs.unito.it/index.php/JLMI"}, "notes": "Rivista open access dell'Università di Torino su OJS: tutti gli articoli dal 2022 (vol. 1) con PDF, metadati completi da OAI-PMH (autori, DOI, volume, fascicolo, pagine). Sono inclusi anche i Foreword dei fascicoli."},
		{"match": ["mdpi.com/journal/laws"], "adapter": "mdpi", "params": {"issn": "2075-471X", "journal": "laws"}, "notes": "Rivista MDPI di diritto, interamente ad accesso aperto (CC BY), a flusso continuo (~150 articoli l'anno). Il sito www.mdpi.com blocca i client non-browser (Akamai), quindi elenco e metadati (titolo, autori, data, volume/fascicolo/numero d'articolo, DOI, abstract) arrivano da Crossref e i PDF dal file server di MDPI (mdpi-res.com), che non ha blocchi."},
		{"match": ["lexambientetrimestrale.it"], "adapter": "lexambiente", "params": {"contentSelector": ".com-content-article__body"}, "notes": "Lexambiente – Rivista trimestrale di diritto penale dell'ambiente (Joomla). Il fascicolo corrente è in home page, i precedenti nella pagina Archivio (dal 2018); per ogni articolo si legge la pagina e si scarica il PDF. Sono compresi gli 'Osservatori' normativo, dottrinale e giurisprudenziale di ogni fascicolo; il fascicolo completo e l'editoriale in PDF unico non vengono scaricati come voci separate."},
		{"match": ["marsafelawjournal.org"], "adapter": "crawl", "params": {"start": "https://www.marsafelawjournal.org/issues/", "issueSelector": "a[href*=\"/issue/issue-\"]", "articleSelector": "article.post", "titleSelector": "h2", "authorsSelector": ".author-name a", "linkSelector": "h2 a[href]", "pdfSelector": "a[href$=\".pdf\"]", "titlePattern": "^\\s*(?<date>\\d{4})", "landingPdfSelector": ".download-pdf a[href]"}, "notes": "Scarica tutti i contributi dei fascicoli (Issue 1, 2015 – Issue 17, 2025): titolo, autori, anno e numero dalla pagina del fascicolo; il PDF dell'articolo si trova nella pagina del contributo ('Download PDF'). Il PDF del fascicolo completo è escluso. Rivista in open access (CC BY-NC-ND), circa 2 fascicoli l'anno."},
		{"match": ["digitalcommons.law.umaryland.edu/mlr"], "adapter": "oai", "params": {"endpoint": "https://digitalcommons.law.umaryland.edu/do/oai/", "set": "publication:mlr", "skipPattern": "^(cover( page)?( and| &)?( front matter| editorial board)?|front matter|back matter|table of contents?|masthead|editorial board|publisher( info)?|copyright|recent and forthcoming|dedication|full issue)(\\s*[-–:].*)?$"}, "notes": "Maryland Law Review (University of Maryland Carey Law) su Digital Commons (bepress), open access: elenco da OAI-PMH con titolo, autori, data, volume e fascicolo. Esclusi copertine, front matter, masthead, editorial board, indici (Table of Contents), pagine di copyright/publisher. I PDF sono dietro Cloudflare: in Zotero vengono scaricati tramite il browser nascosto (fallback); se il download fallisce l'elemento viene creato senza allegato."},
		{"match": ["lawjournal.mcgill.ca"], "adapter": "mcgill-law-journal", "params": {}, "notes": "Scarica tutti i contributi di tutti i fascicoli (dal vol. 1, 1952, al vol. 71, 2026; circa 276 fascicoli e oltre 2.500 PDF: la prima esecuzione è lunga, conviene impostare un anno di partenza). Metadati dalla pagina del fascicolo: titolo, autori, volume, numero, anno, pagina iniziale, tipo di contributo (nel campo Extra se diverso da 'Article'). La rivista è ora in open access; i PDF (file '.abs_.pdf') contengono l'articolo completo."},
		{"match": ["rivistadidirittodeimedia.it", "medialaws.eu"], "adapter": "media-laws", "params": {}, "notes": "La rivista 'MediaLaws – Rivista di diritto dei media' ha ora un sito proprio (rivistadidirittodeimedia.it); medialaws.eu è il blog/portale (commenti, news, call) e non viene scaricato. Un post per articolo (saggi, note, cronache, recensioni, editoriali; dal 2017, circa 60 l'anno): titolo, data, fascicolo (es. '1/2026', 'Special Issue II/2025'; gli articoli in 'Anteprime' non hanno ancora il numero), autori e PDF dalla pagina dell'articolo."},
		{"match": ["repository.law.umich.edu/mjil"], "adapter": "oai", "params": {"endpoint": "https://repository.law.umich.edu/do/oai/", "set": "publication:mjil", "skipPattern": "^(cover( page)?( and| &)?( front matter| editorial board)?|front matter|back matter|table of contents?|masthead|editorial board|publisher( info)?|copyright|recent and forthcoming|dedication|full issue)(\\s*[-–:].*)?$"}, "notes": "Michigan Journal of International Law (University of Michigan Law School) su Digital Commons (bepress), open access: elenco da OAI-PMH con titolo, autori, data, volume e fascicolo. Esclusi copertine, front matter, masthead, editorial board, indici (Table of Contents), pagine di copyright/publisher. I PDF sono dietro Cloudflare: in Zotero vengono scaricati tramite il browser nascosto (fallback); se il download fallisce l'elemento viene creato senza allegato. DOI presenti per i fascicoli recenti."},
		{"match": ["riviste.unimi.it/index.php/milanlawreview"], "adapter": "ojs", "params": {"base": "https://riviste.unimi.it/index.php/milanlawreview"}, "notes": "Rivista open access dell'Università di Milano (OJS): tutti gli articoli dal 2020 con PDF e metadati da OAI-PMH. Due fascicoli l'anno."},
		{"match": ["network-industries.org/network-industries-quarterly"], "adapter": "network-industries-quarterly", "params": {"base": "https://www.network-industries.org", "query": {"categories_exclude": "12"}}, "enabled": false, "notes": "[Disattivata: i numeri recenti esistono solo come PDF del fascicolo completo] Solo la sezione Network Industries Quarterly del sito (un post per fascicolo; esclusa la categoria 'Publications', che contiene schede di libri). Per i fascicoli 2015–2023 (fino a giugno 2023) ogni articolo ha un proprio PDF e viene importato con titolo e autori; per i fascicoli 2012–2015 e da ottobre 2023 in poi esiste solo il PDF del fascicolo completo, importato come un unico item (titolo = tema del fascicolo, 'Full issue' in Extra). Volume e numero sono ricavati dal nome del PDF del fascicolo; data = data del post."},
		{"match": ["nomos-leattualitaneldiritto.it"], "adapter": "wordpress", "params": {"base": "https://www.nomos-leattualitaneldiritto.it", "query": {"categories_exclude": "1,5,21,146,3888,3904,3905,3906,3907,3908,3909,3910,3911,3912,3913,3914,3915,3916,3917,3918,3919,3920,3921,3922,3923,3924,3925,3926,3927,3928,3929,3930,3931,3932,3933,3934,3935,3936,3937,3938,3939,3940,3941,3942,3943,3944,3945,3946,3947,3948,3949,3950,3951,4119,4120,4121"}, "titlePattern": "^(?:[A-ZÀ-Ý][A-ZÀ-Ý .'-]+:\\s*)?(?<authors>[^,]{3,60}?),\\s+(?<title>.+)$"}, "notes": "Un post WordPress per contributo (saggi, note, cronache costituzionali italiane ed estere, osservatori, recensioni, contributi a convegni, anticipazioni dei fascicoli), con il PDF linkato nel testo. Sono esclusi: news, post-indice dei fascicoli ('Nomos 1-2026', che ripetono i PDF), indici, documentazione (audizioni, sentenze) e tutta la sezione Parlalex. Titolo e autore sono separati dal titolo del post ('Autore, Titolo'; per le cronache 'PAESE: Autore, Titolo'); se gli autori sono più di uno solo il primo viene riconosciuto e gli altri restano nel titolo. Data = data di pubblicazione online; il numero del fascicolo non è ricavato. Volume elevato: circa 250 contributi l'anno, dal 2012."},
		{"match": ["nuoveautonomie.it"], "adapter": "wordpress", "params": {"base": "https://www.nuoveautonomie.it", "query": {"categories_exclude": "2,48,54,210"}}, "notes": "Un post per articolo (saggi, speciali, 'La dottrina dialoga con la giurisprudenza', 'L'angolo delle libertà', recensioni, anticipazioni) con il link 'Scarica PDF': titolo, autori (plugin co-autori), data di pubblicazione online; il numero del fascicolo non è ricavato. Pubblicati così i fascicoli dal n. 3/2020 in poi. Esclusi: i post dell''Archivio' (PDF del fascicolo completo, 2009–2026), le news/eventi e la collana. I fascicoli 2009–2020 esistono solo come PDF completi e quindi non vengono scaricati."},
		{"match": ["riviste.unimi.it/index.php/nad"], "adapter": "ojs", "params": {"base": "https://riviste.unimi.it/index.php/NAD"}, "notes": "Rivista open access dell'Università di Milano (OJS), pubblicazione continua in due fascicoli annui: saggi, speciali, cronache, note a sentenza e recensioni, tutti con PDF e metadati da OAI-PMH."},
		{"match": ["opiniojurisincomparatione.org"], "adapter": "opinio-juris-in-comparatione", "params": {}, "notes": "Scarica tutti gli articoli dei fascicoli (dal 2009, circa 270 PDF) leggendo l'indice di ciascun fascicolo: titolo, autori, anno, volume e numero (per i fascicoli speciali il nome del fascicolo nel campo Numero). Gli articoli in 'PRE-PRINT' vengono importati senza numero di fascicolo; se poi confluiscono in un fascicolo regolare non vengono duplicati (stessa pagina articolo). Il PDF del fascicolo completo è escluso."},
		{"match": ["rivistaoidu.net"], "adapter": "ordine-internazionale-diritti-umani", "params": {}, "notes": "Rivista ad accesso aperto (5 fascicoli l'anno). Vengono scaricati gli articoli di ogni fascicolo (il numero corrente è in home page, gli altri in 'Numeri precedenti') e i contributi degli Osservatori (note di giurisprudenza, una pagina per osservatorio); si possono escludere gli Osservatori con il parametro \"osservatori\": false. Non vengono scaricati gli abstract separati, gli Speciali, i Quaderni e le Monografie. Autori ricavati dall'indice (nomi in maiuscolo: la divisione nome/cognome dei cognomi composti può essere imprecisa). Data = data del fascicolo; per gli Osservatori solo l'anno."},
		{"match": ["osservatorioaic.it"], "adapter": "crawl", "params": {"start": "https://www.osservatorioaic.it/it/osservatorio/ultimi-contributi-pubblicati", "articleSelector": "article.item", "linkSelector": "h2 a", "titleSelector": "h2", "authorsSelector": ".category-name a", "titlePattern": "NUMERO E ARGOMENTI:.*?(?<date>\\b\\d{1,2}/(?:19|20)\\d\\d\\b)", "nextSelector": ".pagination a[title=\"Avanti\"]", "contentSelector": "[itemprop=articleBody]", "landing": true, "skipPattern": "^(Supplemento|Fascicolo)\\b"}, "notes": "Rivista bimestrale online dell'Associazione Italiana dei Costituzionalisti, stessa piattaforma Joomla della Rivista AIC e stessa configurazione. Si legge l'elenco 'Ultimi contributi pubblicati' e da ogni pagina articolo si scarica il PDF. Data = anno del fascicolo (es. 5/2026); il numero del fascicolo non viene registrato. Sono compresi note a sentenza, interventi a seminari e rassegne (es. 'Novità editoriali')."},
		{"match": ["journals.uniurb.it/index.php/pea"], "adapter": "ojs", "params": {"base": "https://journals.uniurb.it/index.php/pea", "excludeSets": ["pea:CI"]}, "notes": "Rivista open access dell'Università di Urbino (OJS): articoli, studi, contributi stranieri, recensioni con PDF e metadati da OAI-PMH; esclusa la sezione \"Copertina e indice\". Dal 2026 c'è anche una \"serie speciale - e-book\" (V. 1 N. 1 2026) con contributi in inglese di autori dell'Asia centrale/Europa orientale, che viene scaricata come il resto."},
		{"match": ["papersdidirittoeuropeo.eu"], "adapter": "crawl", "params": {"start": "https://www.papersdidirittoeuropeo.eu/category/rivista/", "issueSelector": "h2.entry-title a", "issueNext": "a.next.page-numbers", "titlePattern": "^(?<authors>(?:\\p{Lu}[\\p{L}’'.\\-]+(?:\\s+(?:\\p{Lu}[\\p{L}’'.\\-]+|de|del|della|di|da|dal|van|von)){1,3}(?:\\s*,\\s*|\\s+(?:and|e|&)\\s+))*\\p{Lu}[\\p{L}’'.\\-]+(?:\\s+(?:\\p{Lu}[\\p{L}’'.\\-]+|de|del|della|di|da|dal|van|von)){1,3}),\\s*(?<title>.+)$", "skipPattern": "^(papers di diritto europeo|download|editoriale$)"}, "notes": "Rivista ad accesso aperto (2 fascicoli l'anno più numeri speciali). Ogni fascicolo è un articolo WordPress con i PDF dei singoli contributi: vengono scaricati i singoli articoli (titolo e autori dall'indice, anno dal titolo del fascicolo, campo 'numero' = nome del fascicolo). Il PDF dell'intero fascicolo viene saltato; per i fascicoli 2011-2020 il sito pubblica solo il PDF del fascicolo intero, quindi non viene importato nulla di quegli anni."},
		{"match": ["personaemercato.it"], "adapter": "crawl", "params": {"start": "https://www.personaemercato.it/category/persona-e-mercato-rivista-on-line/", "issueSelector": "h2.entry-title a", "issueNext": ".previous a", "articleSelector": ".post-entry li", "titlePattern": "^(?<authors>(?:(?:\\p{Lu}\\.\\s*)+\\p{Lu}[\\p{L}’'\\-]+(?:\\s+\\p{Lu}[\\p{L}’'\\-]+){0,4}|\\p{Lu}[\\p{Lu}’'\\-]+(?:\\s+\\p{Lu}[\\p{Lu}’'\\-]+)+)(?:\\s*(?:,|–|\\be\\b)\\s*(?:(?:\\p{Lu}\\.\\s*)+\\p{Lu}[\\p{L}’'\\-]+(?:\\s+\\p{Lu}[\\p{L}’'\\-]+){0,4}|\\p{Lu}[\\p{Lu}’'\\-]+(?:\\s+\\p{Lu}[\\p{Lu}’'\\-]+)+))*)(?:\\s*\\([^)]*\\))?\\s*,\\s*(?<title>.+)$", "skipPattern": "^persona e mercato"}, "notes": "Rivista ad accesso aperto diretta da G. Vettori (4 fascicoli l'anno, dal 2009). Ogni fascicolo è un articolo della categoria 'Persona e Mercato - Rivista on-line' con l'elenco dei contributi in PDF: vengono scaricati i singoli contributi (compresa la rubrica 'Diritto e nuove tecnologie' dell'OGID). Sono esclusi il PDF del fascicolo intero e la versione 'libretto', le News, le Note redazionali, i Quaderni e le Monografie. Titolo e autori dall'indice ('G. VETTORI, Titolo'), anno dal titolo del fascicolo, campo 'numero' = titolo del fascicolo."},
		{"match": ["ojs.aduei.com/index.php/pad"], "adapter": "oai", "params": {"endpoint": "https://ojs.aduei.com/index.php/pad/oai", "landingPattern": "/article/view/[^/]+$", "landing": true}, "notes": "Rivista open access (OJS, Aduei): elenco articoli da OAI-PMH, metadati (titolo nella lingua giusta, autori, data, volume, fascicolo, pagine) e PDF dalla pagina di ogni articolo. Alcuni fascicoli (2020, V. 9 N. 1 2024) non hanno il PDF sul sito: quegli articoli vengono creati senza allegato."},
		{"match": ["aisdue.eu"], "adapter": "wordpress", "params": {"base": "https://www.aisdue.eu", "query": {"categories": "161,162,163,233"}, "titlePattern": "^(?<authors>\\p{Lu}[\\p{Lu}\\s.’'\\-]+(?:(?:,|\\se\\s)\\s*\\p{Lu}[\\p{Lu}\\s.’'\\-]+)*)(?:\\s[–-]\\s*\\p{Lu}[\\p{Lu}\\s.’'\\-]+)*\\s*[,–]\\s*(?<title>.+)$", "perPage": 30}, "notes": "Quaderni AISDUE (ISSN 2975-2698) è la rivista dell'Associazione italiana studiosi di diritto dell'Unione europea: i fascicoli (3 l'anno più numeri speciali) raccolgono i contributi pubblicati prima come singoli post sul sito, ciascuno con il proprio PDF. Vengono scaricati solo i post delle categorie Articoli, Note e commenti, Atti convegni AISDUE (serie speciale) e BlogDUE che hanno un PDF; sono esclusi news, bandi, convegni, verbali, bibliografie, Forum e il PDF del fascicolo completo. Titolo e autori dal titolo del post ('NOME COGNOME, Titolo'); data = data di pubblicazione del post (non viene indicato il fascicolo). Sono inclusi anche i 'Post di AISDUE' del 2019-2020 che precedono la rivista e qualche documento redazionale (criteri redazionali, presentazioni)."},
		{"match": ["qdsp.it"], "adapter": "crawl", "params": {"start": "https://www.qdsp.it/category/archivio/", "issueSelector": "h2.entry-title a", "issueNext": "a.next.page-numbers", "articleSelector": ".entry-content p, .entry-content li", "titlePattern": "^(?<authors>\\p{Lu}[\\p{L}’'.\\-]+(?:\\s+(?:\\p{Lu}[\\p{L}’'.\\-]+|d[a-z]{0,4}[’']?|van|von)){1,3}(?:(?:\\s*,\\s*|\\s+[eE]d?\\s+)\\p{Lu}[\\p{L}’'.\\-]+(?:\\s+(?:\\p{Lu}[\\p{L}’'.\\-]+|d[a-z]{0,4}[’']?|van|von)){1,3})*)(?:\\s*,\\s*|\\s+[–-]\\s+)(?<title>\\S.*)$", "skipPattern": "^(indic|gli autori|è possibile|qui$|pdf cliccando|appendice iconografica|il volume affronta)"}, "notes": "Rivista ad accesso aperto dell'Università Cattolica (dir. M. de Leonardis), 2 fascicoli l'anno dal 2011. Ogni fascicolo è un articolo WordPress con il PDF di ciascun contributo: vengono scaricati i singoli contributi (introduzione del direttore compresa); sono esclusi indice, 'Gli Autori', appendici e il PDF integrale. Titolo e autori dall'indice ('Nome Cognome, Titolo' o 'Nome Cognome – Titolo'), anno dal titolo del fascicolo, campo 'numero' = 'Fascicolo N | anno'. I PDF dei fascicoli recenti sono pesanti (circa 20-25 MB l'uno)."},
		{"match": ["sidiblog.org"], "adapter": "wordpress", "params": {"base": "https://www.sidiblog.org", "requirePdf": false, "pdfSelector": "a.jc-no-pdf", "contentSelector": "title", "perPage": 50, "htmlToPdf": true}, "notes": "I Quaderni di SIDIBlog sono la raccolta annuale (in volume, Editoriale Scientifica) dei post pubblicati su SIDIBlog, il blog della SIDI. Vengono importati i singoli post del blog, che sono i contributi poi raccolti nei Quaderni: sono solo in HTML, quindi il plugin salva la pagina web come snapshot (nessun PDF; i PDF linkati nei post sono fonti, come sentenze e documenti, e vengono ignorati). Data = data del post; autori non estratti (sono nel primo paragrafo del testo, in forma non uniforme). I volumi annuali completi dei Quaderni (PDF di tutto il volume, parte su editorialescientifica.it) non vengono scaricati."},
		{"match": ["rqda.eu"], "adapter": "quadrimestrale-diritto-dellambiente", "params": {}, "notes": "Rivista ad accesso aperto (dal 2010; 3 fascicoli l'anno più numeri speciali, pubblicati con ritardo: il n. 2/2025 è uscito ad agosto 2026). Ogni contributo è un articolo WordPress con il PDF scaricabile tramite Download Manager (link ?dl_id=N). Vengono scaricati tutti i contributi; sono esclusi i post con il fascicolo completo ('Anno 2025 – RIVISTA NUMERO 2', 'Numero Speciale S1/2026'), gli indici, le news e i duplicati in inglese. Anno e numero dalla categoria del fascicolo ('Rivista numero 2 2025' → 2025, n. 2; numeri speciali 'S1'); autori dal titolo del post ('NOME COGNOME – Titolo')."},
		{"match": ["questeistituzioni.it"], "adapter": "wordpress", "params": {"base": "https://questeistituzioni.it"}, "notes": "Rivista trimestrale ad accesso aperto. Sul sito ogni contributo (dal 2021) è un articolo WordPress con il PDF allegato: vengono scaricati tutti i contributi, editoriali compresi. Data = data di pubblicazione online (coincide con l'uscita del fascicolo); numero del fascicolo e autori non disponibili nei metadati (gli autori sono nel testo 'di Nome Cognome'). I fascicoli completi (tipo 'portfolio', dal n. 1/2021) non vengono scaricati. Gli anni precedenti al 2021 non sono sul sito."},
		{"match": ["rivistadellaregolazionedeimercati.it"], "adapter": "giappichelli", "params": {"base": "https://www.rivistadellaregolazionedeimercati.it"}, "notes": "Rivista semestrale ad accesso aperto (CC BY-NC-SA) ospitata sulla piattaforma di Giappichelli. Vengono scaricati i singoli articoli (editoriali, saggi, note, recensioni) con titolo, autori (senza affiliazione), data e numero del fascicolo. Il PDF del singolo articolo è linkato solo dalla pagina dell'articolo, che viene letta per ogni articolo nuovo. Alcuni articoli dei primissimi fascicoli (2014) hanno solo il PDF dell'intero fascicolo: vengono registrati senza PDF."},
		{"match": ["rivistaaic.it"], "adapter": "crawl", "params": {"start": "https://www.rivistaaic.it/it/rivista/ultimi-contributi-pubblicati", "articleSelector": "article.item", "linkSelector": "h2 a", "titleSelector": "h2", "authorsSelector": ".category-name a", "titlePattern": "NUMERO E ARGOMENTI:.*?(?<date>\\b\\d{1,2}/(?:19|20)\\d\\d\\b)", "nextSelector": ".pagination a[title=\"Avanti\"]", "contentSelector": "[itemprop=articleBody]", "landing": true, "skipPattern": "^(Supplemento|Fascicolo)\\b"}, "notes": "Rivista trimestrale dell'Associazione Italiana dei Costituzionalisti (Joomla). Si legge l'elenco 'Ultimi contributi pubblicati' (20 articoli per pagina, dal più recente) e da ogni pagina articolo si scarica il PDF ('Visualizza'). Il fascicolo (es. 3/2026) viene ricavato dall'etichetta 'NUMERO E ARGOMENTI' e dà solo l'anno come data; il numero del fascicolo non viene registrato. I PDF dei fascicoli completi e dei supplementi non vengono scaricati. Gli autori arrivano dall'elenco (campo 'di:')."},
		{"match": ["europeanlitigation.eu"], "adapter": "wordpress", "params": {"base": "https://europeanlitigation.eu", "query": {"categories": "191,193,195,778"}, "pdfSelector": "a[href*=\"europeanlitigation.eu/wp-content/uploads/\"][href$=\".pdf\"]"}, "notes": "Rivista ad accesso aperto (dal 2023) pubblicata in tre lingue (italiano, inglese, francese): ogni contributo compare in tre post con lo stesso PDF, per questo vengono letti solo i post della versione italiana (categorie Articoli, Segnalazioni, Recensioni, Commenti, compresi i fascicoli speciali). Ogni contributo ha il suo PDF (in lingua originale). WooCommerce sul sito è solo un residuo del tema: nulla è a pagamento. Autori non estratti (solo nella pagina, meta 'author'); data = data di pubblicazione del post; nessun numero di fascicolo."},
		{"match": ["diritticomparati.it"], "adapter": "crawl", "params": {"start": "https://www.diritticomparati.it/rivista-quadrimestrale-1-2017", "issueSelector": "li.menu-item-object-rivista-trimestrale > a, .iksm-term--child a.iksm-term__link", "articleSelector": ".uncode_text_column a[href*=\".pdf\"]", "titlePattern": "^(?<authors>[^,]*?\\p{Lu}{2,}[^,]*?(?:,\\s*[^,]*?\\p{Lu}{2,}[^,a-z]*)*)\\s*,\\s*(?<title>.+)$", "skipPattern": "^(download|rivista di diritti comparati)"}, "notes": "Rivista quadrimestrale ad accesso aperto (più special issue) pubblicata sul sito del blog Diritti Comparati. Vengono scaricati i singoli articoli dei fascicoli, elencati nel menu 'Archivio Rivista' e nella voce di menu 'RIVISTA' (fascicolo più recente); il blog, i vlog e le news non vengono importati. Titolo e autori dall'indice ('AUTORE, Titolo'), anno e 'numero' dall'etichetta del fascicolo (es. '1/2026', 'SPECIAL ISSUE VIII (2026)'). I fascicoli 2017-2018 sono solo in PDF unico e vengono saltati. Limite: il fascicolo raggiungibile solo dalla voce 'RIVISTA' (oggi lo Special Issue IX-2 2026) viene importato senza data e con numero 'RIVISTA', finché la redazione non lo aggiunge all'archivio."},
		{"match": ["rivistadirittoalimentare.it"], "adapter": "rivista-di-diritto-alimentare", "params": {}, "notes": "Rivista trimestrale ad accesso aperto dell'AIDA (dal 2007), con Quaderni monografici. Il sito WordPress è solo una vetrina: i fascicoli sono file statici in /rivista/<numero>/ con un indice testuale (sommario.txt) e un PDF per ogni contributo; per questo il catalogo WordPress risulta senza PDF. Vengono scaricati tutti i contributi dei fascicoli e dei Quaderni (numero '2 (Quaderno)'); sono esclusi i fascicoli di indici annuali e il PDF del fascicolo completo. Titolo, autori e sezione (nel campo Extra) dall'indice; data = anno. Gli accenti scritti come apostrofo nell'indice ('qualita'') vengono ripristinati."},
		{"match": ["ojs.unito.it/index.php/rsajournal"], "adapter": "ojs", "params": {"base": "https://ojs.unito.it/index.php/rsajournal", "excludeSets": ["rsajournal:CP", "rsajournal:Notes"]}, "notes": "Rivista annuale open access dell'Associazione Italiana di Studi Nord-Americani (OJS Torino): articoli, sezioni speciali, recensioni e interventi dal 1990, con PDF e metadati da OAI-PMH; escluse pagina del copyright e note sui collaboratori."},
		{"match": ["scienzaepolitica.unibo.it"], "adapter": "ojs", "params": {"base": "https://scienzaepolitica.unibo.it", "excludeSets": ["scienzaepolitica:Coll"]}, "notes": "Rivista open access dell'Università di Bologna (OJS senza index.php, OAI su https://scienzaepolitica.unibo.it/oai): saggi, temi monografici, forum e recensioni con PDF e metadati da OAI-PMH; esclusa la pagina \"Hanno collaborato a questo numero\"."},
		{"match": ["riviste.unimi.it/index.php/sed"], "adapter": "ojs", "params": {"base": "https://riviste.unimi.it/index.php/SED"}, "notes": "Rivista open access dell'Università di Milano (OJS): articoli, dossier ed editoriali dal 2016 con PDF e metadati da OAI-PMH. Due fascicoli l'anno."},
		{"match": ["ste.unibo.it"], "adapter": "ojs", "params": {"base": "https://ste.unibo.it", "mode": "archive"}, "notes": "Rivista open access dell'Università di Bologna (OJS senza index.php): un volume l'anno. Si scorre l'archivio dei volumi dal più recente; metadati (autori, data, volume, pagine, DOI) e PDF dalla pagina di ogni articolo, che offre anche galley HTML e traduzioni."},
		{"match": ["clasf.org/browse-the-complrev", "clasf.org/complrev", "clasf.org/complrev-call-for-papers"], "adapter": "the-competition-law-review", "params": {}, "notes": "Rivista ad accesso aperto del Competition Law Scholars Forum (CLaSF), dal 2004, ancora attiva (ultimo fascicolo Vol. 16 n. 2, 2026). Il vecchio indirizzo clasf.org/CompLRev/ porta a una call for papers: l'archivio è in 'Browse the Review', un albero di file (WP-Filebase) caricato via AJAX. Vengono scaricati tutti i contributi (editoriali compresi) di tutti i fascicoli, con titolo, autori, abstract, volume e numero. Il sito non indica date: l'anno viene dalla data di caricamento del PDF (fascicoli dal 2016) o, per i fascicoli 2004-2015 migrati in blocco nel 2016, da una tabella ricavata dalle copertine."},
		{"match": ["fondazionecapriglione.luiss.it/index_file/page860.htm", "rtde.luiss.it"], "adapter": "trimestrale-diritto-delleconomia", "params": {}, "enabled": false, "notes": "[Disattivata: i numeri recenti esistono solo come PDF del fascicolo completo] rtde.luiss.it rimanda alla pagina della rivista sul sito della Fondazione Gerardo Capriglione. La rivista pubblica solo il PDF dell'intero fascicolo (numeri trimestrali e supplementi, 2012-oggi), non i singoli articoli: ogni fascicolo viene importato come un unico elemento ('Rivista trimestrale di diritto dell'economia, Numero 2 2026'), senza autori. I fascicoli 2009-2011 (pagina separata, supplementi senza anno) non sono inclusi."},
		{"match": ["rtsa.eu"], "adapter": "trimestrale-scienza-amministrazione", "params": {}, "notes": "Rivista trimestrale ad accesso aperto (CC BY-NC-ND), sito statico (non OJS, nonostante il fingerprint). Vengono scaricati i PDF dei singoli articoli di tutti i fascicoli dal 2016 (compresi i supplementi), con titolo, anno, numero del fascicolo e DOI (mEDRA, 10.32049/RTSA…). Gli autori non vengono estratti."},
	],

	/** "https://www.example.org/journal/" → "example.org/journal" */
	key(url) {
		try {
			let u = new URL(url);
			let p = (u.hostname.replace(/^www\./, '') + u.pathname).toLowerCase().replace(/\/+$/, '');
			let prev;
			do {
				prev = p;
				p = p.replace(/\/(index(\.html?|\.php)?|homepage|home|it|en|it_it|en_us)$/, '');
			} while (p !== prev);
			return p;
		}
		catch (e) {
			return '';
		}
	},

	/** Profile of the site of url ({adapter, params, notes, enabled}), or null */
	find(url) {
		let key = this.key(url);
		if (!key) return null;
		let best = null, bestLen = 0;
		for (let site of this.SITES) {
			for (let m of site.match) {
				if ((key === m || key.startsWith(m + '/')) && m.length > bestLen) {
					best = site;
					bestLen = m.length;
				}
			}
		}
		if (!best) return null;
		let { match, ...profile } = best;
		return JSON.parse(JSON.stringify(profile));
	},

	slugify(title) {
		return String(title || '').normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
			.replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'rivista';
	},
};

if (typeof module !== 'undefined') module.exports = { JCProfiles };
